### ISSUE TITLE
"Directions" translation in Italian

### ISSUE THREAD

**Issue by NonnEmilia** [vigji/categigi2020#3]
I'm not sure about "Direzioni"... Maybe could it be better "Indicazioni" or "Luoghi" or even "Location"?

https://github.com/vigji/categigi2020/blob/97e4bc33135d618d33519d5e78b5f80842f98358/index.html#L23

"Indicazioni stradali" is definitely too long for a footer menu.

**Comment by vigji** [comment]
fixed
